language: cpp

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug
  - TRAVIS_BUILD_TYPE=Release

before_script:
  # install a recent cmake, lua 5.1, ruby and python 
  - sudo add-apt-repository -y ppa:robotology/ppa
  - sudo apt-get update
  - sudo apt-get install cmake liblua5.1-dev python-dev ruby-dev libace-dev libgsl-dev
  
  - cd ..
  # install yarp
  - git clone https://github.com/robotology/yarp
  - cd yarp
  - mkdir build
  - cd build
  - cmake -DCREATE_LIB_MATH:BOOL=ON -DCREATE_SHARED_LIBRARY:BOOL=ON -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE}  ..
  - make
  - sudo make install
  - sudo ldconfig
  - cd ../..
  
  # configure robot-testing framework
  - mkdir build 
  - cd build 
  - cmake -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DENABLE_LUA_PLUGIN:BOOL=ON -DENABLE_PYTHON_PLUGIN:BOOL=ON -DENABLE_RUBY_PLUGIN:BOOL=ON -DENABLE_WEB_LISTENER:BOOL=ON -DENABLE_MIDDLEWARE_PLUGINS ..
  
script: 
  - make
  # test install/uninstall
  - sudo make install

notifications:
  email:
    - pegua1@gmail.com
